chat: chat.cpp ./librerias/SocketFlujo.cpp ./librerias/SocketFlujo.hpp ./librerias/Paquete.cpp ./librerias/Paquete.hpp
	g++ chat.cpp -Wall -std=c++11 -lcrypto ./librerias/Paquete.cpp ./librerias/SocketFlujo.cpp -o chat

